In [ ]:
import numpy as np

**Basic Array Creation**

In [ ]:
arr=np.array([1,2,3,4,5])
arr
#in array function we pass the list

array([1, 2, 3, 4, 5])

**List And Array Difference**

*   list contains hetergogenous but not array
*   list is slow wherease array is fast
*   list does not support matrix but array support it







In [ ]:
a=[1,2,3,4,5,'radhe radhe']
#this is list there is heterogeneous elements
a

[1, 2, 3, 4, 5, 'radhe radhe']

In [ ]:
#and if pass this list in an array we got error
np.array(a)

array(['1', '2', '3', '4', '5', 'radhe radhe'], dtype='<U21')

Vector and Matrix
*   vector is just a 1D array
*   matrix is just a 2D array




In [ ]:
#list does not support matrix wherease array support matrix
l=[[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

Array Generation Function

In [ ]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
#array containing only zeroes
arr=np.zeros((6,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#array containing only ones
arr=np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#linspace is a function which we used to find the number between two number with equal linear space between the two numbers
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

**Random Generation Function**

In [ ]:
#this is the random function in which this is rand which gives us random number between -1 to +1 and it is used in normalization
np.random.rand(10)

array([0.23906352, 0.04574987, 0.38941863, 0.94778001, 0.38543173,
       0.54650533, 0.49486791, 0.15707234, 0.32066582, 0.11291342])

In [ ]:
#this is the random function in which there is randn which gives us random number between -3 to +3 and it is used in standardization
np.random.randn(10)

array([-1.26999545e+00, -2.06823854e-01,  1.00970190e+00,  1.28900995e-01,
       -3.42861042e-01, -2.23208828e-01, -8.40106048e-01,  1.16460962e-03,
        2.75322025e-01, -4.21485228e-03])