In [2]:
import numpy as np

**Basic Array Creation**

In [3]:
arr=np.array([1,2,3,4,5])
arr
#in array function we pass the list

array([1, 2, 3, 4, 5])

**List And Array Difference**

*   list contains hetergogenous but not array
*   list is slow wherease array is fast
*   list does not support matrix but array support it







In [4]:
a=[1,2,3,4,5,'radhe radhe']
#this is list there is heterogeneous elements
a

[1, 2, 3, 4, 5, 'radhe radhe']

In [5]:
#and if pass this list in an array we got error
np.array(a)

array(['1', '2', '3', '4', '5', 'radhe radhe'], dtype='<U21')

Vector and Matrix
*   vector is just a 1D array
*   matrix is just a 2D array




In [6]:
#list does not support matrix wherease array support matrix
l=[[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

Array Generation Function

In [8]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [9]:
#array containing only zeroes
arr=np.zeros((6,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
#array containing only ones
arr=np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
#linspace is a function which we used to find the number between two number with equal linear space between the two numbers
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

**Random Generation Function**

In [12]:
#this is the random library in which this is rand function which gives us random number between -1 to +1 and it is used in normalization
np.random.rand(10)

array([0.2962409 , 0.16056982, 0.40582687, 0.88007857, 0.24960435,
       0.61235445, 0.62010823, 0.53661482, 0.38151814, 0.20124702])

In [13]:
#this is the random library in which there is randn function which gives us random number between -3 to +3 and it is used in standardization
np.random.randn(10)

array([-0.05281503,  1.04453941,  0.31244034, -1.53807946,  0.4824014 ,
       -0.51110127,  1.53117424, -0.62164054,  1.70717975, -1.76623486])

In [14]:
#generate random 10 int value between 10 to 20
np.random.randint(10,20,10)

array([16, 15, 14, 10, 13, 11, 16, 17, 15, 15])

**Array Attribute**


In [16]:
arr=np.array([[1,2,3],[2,3,4],[5,6,7]])
arr


array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [18]:
#gives the dimension of the array
arr.shape

(3, 3)